chore:
  - all:
      - changed-files:
          - all-globs-to-any-file:
              - '*'
              - '!deno/**/*'
              - '!gateway/**/*'
              - '!payloads/**/*'
              - '!rest/**/*'
              - '!rpc/**/*'
              - '!tests/**/*'
              - '!utils/**/*'
              - '!voice/**/*'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
          - .husky/**/*
          - scripts/actions/**/*

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - package-lock.json
          - website/package.json
          - website/package-lock.json

'topic:deno':
  - changed-files:
      - any-glob-to-any-file:
          - scripts/deno.mjs
          - scripts/actions/report-deno-not-ran.mjs

'topic:gateway':
  - changed-files:
      - any-glob-to-any-file:
          - gateway/**/*

'topic:payloads':
  - changed-files:
      - any-glob-to-any-file:
          - payloads/**/*

'topic:rest':
  - changed-files:
      - any-glob-to-any-file:
          - rest/**/*

'topic:rpc':
  - changed-files:
      - any-glob-to-any-file:
          - rpc/**/*

'topic:scripts':
  - changed-files:
      - any-glob-to-any-file:
          - scripts/**/*

'topic:tests':
  - changed-files:
      - any-glob-to-any-file:
          - tests/**/*

'topic:utils':
  - changed-files:
      - any-glob-to-any-file:
          - utils/**/*

'topic:voice':
  - changed-files:
      - any-glob-to-any-file:
          - voice/**/*

'topic:globals':
  - changed-files:
      - any-glob-to-any-file:
          - globals.ts

'topic:website':
  - changed-files:
      - any-glob-to-any-file:
          - website/**/*
