name: Bug report
description: Report incorrect or unexpected behavior of discord-api-types, or a mistyped type
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Use Discord for questions: https://discord.gg/djs

  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Please describe the problem you are having in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce with below code sample:
        1. do thing
        2. it broke :c
    validations:
      required: true

  - type: textarea
    id: codesample
    attributes:
      label: Code sample
      description: Include a reproducible, minimal code sample. This will be automatically formatted into code, so no need for backticks.
      render: typescript
      placeholder: |
        Your code sample should be...
        ... Minimal - Use as little code as possible that still produces the same problem (and is understandable)
        ... Complete - Provide all parts someone else needs to reproduce your problem
        ... Reproducible - Test the code you're about to provide to make sure it reproduces the problem

  - type: input
    id: types-version
    attributes:
      label: Package version
      description: Which version of the package are you using? Run `npm list discord-api-types` in your project directory and paste the output.
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime
      description: What runtime are you using?
      options:
        - Node.js
        - Deno
        - Bun
        - Other / Browser
    validations:
      required: true

  - type: input
    id: runtime-version
    attributes:
      label: Runtime version
      description: |
        Which version of your runtime of choice are you using?
        If you are using TypeScript, please include its version (`npm list typescript`) as well.
      placeholder: |
        For Node.js: Run `node --version` in your project directory and paste the output.
        For Deno: Run `deno --version` in your project directory and paste the output.
        For Bun: Run `bun --version` in your project directory and paste the output.
        For Other / Browser: Find the version in your runtime of choice and paste it here.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority this issue should have
      description: Please be realistic. If you need to elaborate on your reasoning, please use the Issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed soon)
        - High (immediate attention needed)
    validations:
      required: true
