name: Website build check

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build_website:
    name: 'Website build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/eslint.json" && echo "::add-matcher::.github/problemMatchers/tsc.json"

      - name: Check for any website changes
        id: website_files_changed
        uses: tj-actions/changed-files@v18.7
        with:
          files: website/**/*

      - name: Install common dependencies
        if: steps.website_files_changed.outputs.any_changed == 'true'
        run: npm ci

      - name: Install website dependencies
        if: steps.website_files_changed.outputs.any_changed == 'true'
        run: pushd website && npm ci && popd

      - name: Check lint on discord-api-types/website
        if: steps.website_files_changed.outputs.any_changed == 'true'
        run: pushd website && npm run test:lint && popd

      - name: Run build on website
        if: steps.website_files_changed.outputs.any_changed == 'true'
        run: pushd website && NODE_OPTIONS=--max_old_space_size=4096 npm run build && popd
