name: Continuous Integration / Deployment

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  testing:
    name: ESLint and TypeScript compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run test:lint

      - name: Run TSC
        run: npm run build:ci

  deno:
    name: Generate Deno compatible code
    runs-on: ubuntu-latest

    needs: testing
    # Run workflow only if testing passes
    if: needs.testing.result == 'success'

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci

      - name: Build Files
        run: npm run build:deno

      - name: Set Git User and Email
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push New Code
        run: |
          git add --all .
          git commit -m "build: deno build for ${GITHUB_SHA}" || true
          git push || true
